version = 1

test_patterns = ["tests/**", "**/*.test.js", "**/*.test.tsx"]

exclude_patterns = ["examples/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  dialect = "typescript"
